apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi-deployment
  labels:
    app: shoppingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: shoppingapi
          image: shoppacr.azurecr.io/shoppingapi:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: environment
                  name: shoppingapi-configmap
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  key: connection_string
                  name: mongo-configmap
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  name: shoppingapi-service
spec:
  selector:
    app: shoppingapi
  ports:
  - protocol: TCP
    port: 80
